# Generated by Django 5.2 on 2025-04-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='enviado_por',
        ),
    ]
