# Generated by Django 5.2 on 2025-05-21 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamadas', '0002_remove_chamada_token_chamada_agora_recording_sid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcricao_texto', models.TextField(blank=True, help_text='Texto transcrito do audio', null=True)),
                ('laudo_preliminar_ia', models.TextField(blank=True, help_text='Laudo gerado por Inteligencia Artificial antes de revisao humana', null=True)),
                ('laudo_final_editado', models.TextField(blank=True, help_text='Laudo final apos edicao do medico responsavel', null=True)),
                ('prompt_utilizado_ia', models.TextField(blank=True, help_text='Prompt exato enviado para a IA gerar o laudo', null=True)),
                ('modelo_ia_utilizado', models.CharField(blank=True, help_text='Modelo de IA utilizado gpt-3.5-turbo', max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao_revisao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE_TRANSCRICAO', 'Pendente Transcrição'), ('TRANSCREVENDO', 'Transcrevendo'), ('ERRO_TRANSCRICAO', 'Erro na Transcrição'), ('PENDENTE_GERACAO_IA', 'Pendente Geração IA'), ('GERANDO_IA', 'Gerando Laudo IA'), ('ERRO_GERACAO_IA', 'Erro na Geração IA'), ('AGUARDANDO_REVISAO', 'Aguardando Revisão Médica'), ('REVISADO_FINALIZADO', 'Revisado e Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE_TRANSCRICAO', max_length=30)),
                ('chamada', models.OneToOneField(help_text='Chamada associada a este laudo', on_delete=django.db.models.deletion.CASCADE, related_name='laudo_medico', to='chamadas.chamada')),
                ('medico_responsavel', models.ForeignKey(blank=True, help_text='Medico que revisou ou e responsavel pelo laudo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudos_sob_resposabilidade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
