# Generated by Django 5.2 on 2025-04-16 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=255)),
                ('token', models.TextField()),
                ('timestamp_inicio', models.DateTimeField()),
                ('timestamp_fim', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_como_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_como_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
