# Generated by Django 5.2 on 2025-05-21 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamada',
            name='token',
        ),
        migrations.AddField(
            model_name='chamada',
            name='agora_recording_sid',
            field=models.CharField(blank=True, help_text='SID da gravacao AGORA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamada',
            name='agora_recording_uid',
            field=models.CharField(blank=True, help_text='UID usado para o bot de gravacao AGORA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamada',
            name='agora_resource_id',
            field=models.CharField(blank=True, help_text='Resourse ID da gravacao AGORA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamada',
            name='arquivo_audio_gravado',
            field=models.FileField(blank=True, null=True, upload_to='gravacoes_chamada/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='canal',
            field=models.CharField(help_text='Nome unico do canal de chamada', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_como_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_como_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('GRAVANDO', 'Gravando'), ('PROCESSANDO_GRAVACAO', 'Processando Gravacao'), ('GRAVADA_AGUARDANDO_LAUDO', 'Gravada - Aguardando Laudo'), ('LAUDO_EM_PROCESSAMENTO', 'Laudo em Processamento'), ('CANCELADA', 'Cancelada'), ('ERRO_GRAVACAO', 'Erro na Gravacao')], default='PENDENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='timestamp_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
